# Google Cloud Build configuration for automatic deployment
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cosmic-canvas:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/cosmic-canvas:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "cosmic-canvas"
      - "--image"
      - "gcr.io/$PROJECT_ID/cosmic-canvas:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--set-env-vars"
      - "NEXT_PUBLIC_TILES_BASE_URL=https://storage.googleapis.com/YOUR-BUCKET-NAME"

images:
  - "gcr.io/$PROJECT_ID/cosmic-canvas:$COMMIT_SHA"

options:
  machineType: "N1_HIGHCPU_8"
